blueprint:
  name: "ðŸŽ™ï¸ Alexa: Dreame Room Cleaning Scripts"
  description: |
    ## ðŸš€ What this blueprint does
    Creates a **custom script** to control your Dreame robot with voice commands via Alexa!
    
    âœ… **Targeted cleaning** of a specific room  
    âœ… **6 cleaning modes** available  
    âœ… **Alexa ready** - no additional configuration needed  
    âœ… **Easily clonable** for multiple rooms  
    
    ## ðŸ  Available Cleaning Modes
    
    | **Mode** | **Description** | **Technology** |
    |:---:|:---:|:---:|
    | ðŸ§¹ **Vacuum** | Vacuum only | Custom Cleaning |
    | ðŸ’§ **Mop** | Mop only | Custom Cleaning |
    | âœ¨ **Cleaning** | Vacuum + Mop | CleanGenius |
    | ðŸ”¥ **Deep Cleaning** | Vacuum + Intensive Mop | CleanGenius Deep |
    
    ## ðŸ“‹ Prerequisites
    1. âœ… Dreame robot configured in Home Assistant
    2. âœ… Room helper created (use the "ðŸ  Room Helper Creation" blueprint)
    3. âœ… Alexa configured (Nabu Casa, Lambda, or Matter)
    
    ## ðŸŽ¯ How to Use It
    
    ### Step 1: Configure the Script
    1. **Select** your robot and required entities
    2. **Enter** the room ID (find it in your room helper)
    3. **Choose** the cleaning mode
    4. **Save** the script with a descriptive name
    
    ### Step 2: Expose to Alexa
    - **Nabu Casa**: Script will appear automatically
    - **Matter**: Add "matter" label to the script
    - **Lambda**: Configure in your AWS setup
    
    ### Step 3: Voice Commands
    **"Alexa, start [script name]"**  
    **"Alexa, open [script name]"**
    
    ## ðŸ’¡ Practical Examples
    
    ### Scenario: Bathroom Cleaning
    1. **Create** script: "Vacuum Bathroom" (Room ID: 5, Mode: Vacuum)
    2. **Clone** script: "Clean Bathroom" (same ID, Mode: Cleaning)
    3. **Commands**: 
       - "Alexa, start vacuum bathroom" 
       - "Alexa, start clean bathroom"
    
    ### Scenario: Complete Kitchen
    - Script 1: "Clean Kitchen" â†’ "Alexa, start clean kitchen"
    - Script 2: "Deep Clean Kitchen" â†’ "Alexa, start deep clean kitchen"
    
    ## âš™ï¸ Technical Notes
    - **CleanGenius**: Advanced mode that combines vacuuming and mopping
    - **Custom Cleaning**: Basic mode for separate vacuuming or mopping
    - **Timeout**: 10 seconds for setting changes
    - **Validation**: Automatically checks that room ID is valid
    
  domain: script
  source_url: https://raw.githubusercontent.com/Magnum9O/HA_BluePrints/main/Dreame/ENG/2_ExposeToAlexa.yaml

  input:
    vacuum_entity:
      name: "ðŸ¤– Dreame Robot"
      description: |
        Select your Dreame robot vacuum cleaner.
        
        ðŸ’¡ **Example**: `vacuum.dreame_l10s_ultra` or `vacuum.xiaomi_vacuum_cleaner`
      selector:
        entity:
          domain: vacuum

    cleangenius_select:
      name: "âœ¨ CleanGenius Entity"
      description: |
        Select the entity that controls your robot's **CleanGenius** mode.
        
        ðŸ’¡ **How to find it**: Look among your robot's `select` entities, usually named:
        - `select.robot_name_cleangenius`
        - `select.dreame_cleangenius`
      selector:
        entity:
          domain: select

    cleaning_mode_select:
      name: "ðŸ”§ Cleaning Mode Entity"
      description: |
        Select the entity that controls **Cleaning Mode** (separate vacuum/mop).
        
        ðŸ’¡ **How to find it**: Look among your robot's `select` entities, usually:
        - `select.robot_name_cleaning_mode`
        - `select.dreame_cleaning_mode`
      selector:
        entity:
          domain: select

  wetness_level_select:
    name: "ðŸ’§ Wetness Level Entity"
    description: |
      Select the entity that controls **Wetness Level**.

      ðŸ’¡ **How to find it**: Look among your robot's `select` entities, usually:
      - `number.robot_name_wetness_level`
      - `number.dreame_wetness_level`
    selector:
      entity:
        domain: select

  cleaning_route_select:
    name: "Cleaning Route Entity"
    description: |
      Select the entity that controls **Cleaning Route**. Standard or Quick.

      ðŸ’¡ **How to find it**: Look among your robot's `select` entities, usually:
      - `select.robot_name_cleaning_route`
      - `select.dreame_cleaning_route`
    selector:
      entity:
        domain: select

    room_id:
      name: "ðŸ  Room ID"
      description: |
        **Enter the numeric ID** of the room you want to clean.
        
        ðŸ” **How to find it**: 
        1. Use the "ðŸ  Room Helper Creation" blueprint
        2. Check the created helper to see "Room Name (**ID**)"
        3. Enter only the number in parentheses
        
        ðŸ“ **Example**: If you see "Kitchen (3)", enter **3**
      selector:
        number:
          min: 0
          max: 999
          mode: box
      default: 0

    cleaning_preset:
      name: "ðŸŽ¯ Cleaning Mode"
      description: |
        Choose your desired cleaning mode:
        
        ðŸ§¹ **Vacuum**: Vacuum only (CleanGenius OFF)
        ðŸ’§ **Mop**: Mop only (CleanGenius OFF)  
        ðŸ§¹ **Vacuum** + ðŸ’§ **Mop**: Vacuum and mop simultaneously (CleanGenius OFF)  
        ðŸ’§ **Mop** after ðŸ§¹ **Vacuum**: Mop after vacuuming (CleanGenius OFF)  
        âœ¨ **Cleaning**: Vacuum + Mop simultaneously (CleanGenius ON)  
        ðŸ”¥ **Deep Cleaning**: Vacuum + Intensive Mop (CleanGenius ON)
      selector:
        select:
          options:
            - label: "ðŸ§¹ Vacuum"
              value: "Vacuum"
            - label: "ðŸ’§ Mop" 
              value: "Mop"
            - label: "ðŸ§¹ Vacuum + ðŸ’§ Mop"
              value: "sweeping and mopping"
            - label: "ðŸ’§ Mop after ðŸ§¹ Vacuum"
              value: "mopping after sweeping"
            - label: "âœ¨ CleanGenius Routine Cleaning"
              value: "Cleaning"
            - label: "ðŸ”¥CleanGenius Deep Cleaning"
              value: "Deep Cleaning"
      default: "sweeping and mopping"

  wetness_level:
    name: "ðŸ’§ Mopping Wetness Level"
    description: |
      **Enter the number of the wetness level for mopping.**
    selector:
      number:
        min: 1
        max: 32
        mode: slider
    default: 25

  cleaning_route:
    name: "Cleaning Route"
    description: |
      Choose your desired cleaning route:
      
      Standard or Quick
    selector:
      select:
        options:
          - label: "Standard"
            value: "standard"
          - label: "Quick"
            value: "quick"
    default: "standard"

icon: mdi:robot-vacuum

mode: single

sequence:
  - variables:
      _vacuum: !input vacuum_entity
      _cleangenius_mode: !input cleangenius_select
      _manual_mode: !input cleaning_mode_select
      _roomid: !input room_id
      _wetness_level_select: !input wetness_level_select
      _wetness_level: !input wetness_level
      _cleaning_route_select: !input cleaning_route_select
      _cleaning_route: !input cleaning_route
      _preset_raw: !input cleaning_preset
      _preset: "{{ (_preset_raw or 'sweeping and mopping') | lower }}"

  # Validate room ID
  - condition: template
    value_template: "{{ (_roomid | int(default=-1)) >= 0 }}"
    alias: "Verify room ID validity"

  # Branch based on preset
  - choose:
      # DEEP CLEANING â†’ CleanGenius deep_cleaning
      - conditions:
          - condition: template
            value_template: "{{ _preset == 'deep cleaning' }}"
        sequence:
          - alias: "Set CleanGenius Deep Cleaning"
            service: select.select_option
            target:
              entity_id: "{{ _cleangenius_mode }}"
            data:
              option: deep_cleaning

          - alias: "Wait for CleanGenius mode change"
            wait_template: >-
              {{ states(_cleangenius_mode) in ['deep_cleaning','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Start deep cleaning room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vacuum }}"
            data:
              segments:
                - "{{ _roomid | int }}"

      # CLEANING  â†’ CleanGenius set to Routine Cleaning, then start
      - conditions:
          - condition: template
            value_template: "{{ _preset == 'cleaning' }}"
        sequence:
          - alias: "Set CleanGenius Routine Cleaning"
            service: select.select_option
            target:
              entity_id: "{{ _cleangenius_mode }}"
            data:
              option: routine_cleaning
          - alias: "Start standard cleaning room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vacuum }}"
            data:
              segments:
                - "{{ _roomid | int }}"

      # VACUUM â†’ CleanGenius OFF â†’ cleaning_mode sweeping â†’ start
      - conditions:
          - condition: template
            value_template: "{{ _preset == 'vacuum' }}"
        sequence:
          - alias: "Disable CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cleangenius_mode }}"
            data:
              option: 'off'

          - alias: "Wait for CleanGenius disable"
            wait_template: >-
              {{ states(_cleangenius_mode) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Set vacuum mode"
            service: select.select_option
            target:
              entity_id: "{{ _manual_mode }}"
            data:
              option: sweeping

          - delay: "00:00:01"

          - alias: "Set cleaning route"
            service: select.select_option
            target:
              entity_id: "{{ _cleaning_route_select }}"
            data:
              option: "{{ _cleaning_route }}"

          - delay: "00:00:01"

          - alias: "Start vacuum room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vacuum }}"
            data:
              segments:
                - "{{ _roomid | int }}"

      # MOP â†’ CleanGenius OFF â†’ cleaning_mode mopping â†’ start
      - conditions:
          - condition: template
            value_template: "{{ _preset == 'mop' }}"
        sequence:
          - alias: "Disable CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cleangenius_mode }}"
            data:
              option: 'off'

          - alias: "Wait for CleanGenius disable"
            wait_template: >-
              {{ states(_cleangenius_mode) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Set mop mode"
            service: select.select_option
            target:
              entity_id: "{{ _manual_mode }}"
            data:
              option: mopping

          - delay: "00:00:01"

          - alias: "Set wetness level"
            service: number.set_value
            target:
              entity_id: "{{ _wetness_level_select }}"
            data:
              option: "{{ _wetness_level }}"

          - delay: "00:00:01"

          - alias: "Set cleaning route"
            service: select.select_option
            target:
              entity_id: "{{ _cleaning_route_select }}"
            data:
              option: "{{ _cleaning_route }}"

          - delay: "00:00:01"

          - alias: "Start mop room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vacuum }}"
            data:
              segments:
                - "{{ _roomid | int }}"

      # Sweeping and Mopping manual â†’ CleanGenius OFF â†’ cleaning_mode mopping â†’ start
      - conditions:
          - condition: template
            value_template: "{{ _preset == 'sweeping and mopping' }}"
        sequence:
          - alias: "Disable CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cleangenius_mode }}"
            data:
              option: 'off'

          - alias: "Wait for CleanGenius disable"
            wait_template: >-
              {{ states(_cleangenius_mode) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Set sweeping and mopping mode"
            service: select.select_option
            target:
              entity_id: "{{ _manual_mode }}"
            data:
              option: sweeping_and_mopping

          - delay: "00:00:01"

          - alias: "Set wetness level"
            service: number.set_value
            target:
              entity_id: "{{ _wetness_level_select }}"
            data:
              option: "{{ _wetness_level }}"

          - delay: "00:00:01"

          - alias: "Set cleaning route"
            service: select.select_option
            target:
              entity_id: "{{ _cleaning_route_select }}"
            data:
              option: "{{ _cleaning_route }}"

          - delay: "00:00:01"

          - alias: "Start sweeping and mopping room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vacuum }}"
            data:
              segments:
                - "{{ _roomid | int }}"

      # mopping after sweeping manual â†’ CleanGenius OFF â†’ cleaning_mode mopping after sweeping â†’ start
      - conditions:
          - condition: template
            value_template: "{{ _preset == 'mopping after sweeping' }}"
        sequence:
          - alias: "Disable CleanGenius"
            service: select.select_option
            target:
              entity_id: "{{ _cleangenius_mode }}"
            data:
              option: 'off'

          - alias: "Wait for CleanGenius disable"
            wait_template: >-
              {{ states(_cleangenius_mode) in ['off','unknown','unavailable','none'] }}
            timeout: "00:00:10"

          - alias: "Set sweeping and mopping mode"
            service: select.select_option
            target:
              entity_id: "{{ _manual_mode }}"
            data:
              option: mopping_after_sweeping

          - delay: "00:00:01"

          - alias: "Set wetness level"
            service: number.set_value
            target:
              entity_id: "{{ _wetness_level_select }}"
            data:
              option: "{{ _wetness_level }}"

          - delay: "00:00:01"

          - alias: "Set cleaning route"
            service: select.select_option
            target:
              entity_id: "{{ _cleaning_route_select }}"
            data:
              option: "{{ _cleaning_route }}"

          - delay: "00:00:01"

          - alias: "Start sweeping and mopping room"
            service: dreame_vacuum.vacuum_clean_segment
            target:
              entity_id: "{{ _vacuum }}"
            data:
              segments:
                - "{{ _roomid | int }}"


    default: []